### PR TITLE
fix: extra characters in default value

### LINKED ISSUE #154: Extra characters in default value
Sometimes, default value may be written as:
*`"table"`
*`'bower_components'`
*`[]`

In first two cases, default be cointain extra quotes, in third case default will be `[`. Please, fix it.

### PR DESCRIPTION
**Pull request by ifedchankau**
Remove extra characters from default value

Closes #154

### CODE REVIEW

File: src/arguments.js [hunk 1]
```diff
@@ -179,33 +180,34 @@ const removeExtraSpaces = (string) => {
...
 * @param {string} string - source string
-* @param {char} char - char for remove
-* @return {*} - string without dot at the end
+* @param {array} array - char for remove
+* @return {*} - string without chars
 */
-const removeCharAtTheEnd = (string, char) => {
-    return string.charAt(string.length - 1) === char ?
-        string.slice(0, string.length - 1) : string;
+const removeCharAtSides = (string, array) => {
```
Comment (romanrostislavovich) [inline src/arguments.js]: I think we need to change this function to `removeCharAtTheStart` or combine it with `removeCharAtTheEnd` (then remove last).  Support both function there is no point

**Review by romanrostislavovich — APPROVED** [review]
+1
